- hosts: localhost 
  vars:
    homedir: "{{ lookup('env', 'HOME') }}"
  tags:
      - install
      - core
  pre_tasks:
    - raw: ansible-galaxy install -r requirements.yml
      tags:
        - always
  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
        - install
        - ssh
    - include_tasks: tasks/git.yml
      tags:
        - install
        - git
    - include_tasks: tasks/homebrew.yml
      tags:
        - install
        - homebrew
    - include_tasks: tasks/node.yml
      tags:
        - install
        - node
    - include_tasks: tasks/npm-pkgs.yml
      tags:
        - install
        - npm
    - include_tasks: tasks/java.yml
      tags:
        - install
        - java
    - include_tasks: tasks/dotfiles.yml
      tags:
        - install
    - include_tasks: tasks/zsh.yml
      tags:
        - zsh
        - install
        - dotfiles
    - include_tasks: tasks/softwareupdate.yml
      tags:
        - install
    - include_tasks: tasks/fonts.yml
      tags:
        - install
        - fonts
    - include_tasks: tasks/macos.yml
      tags:
        - install
        - macos
    - include_tasks: tasks/insomnia.yml
      tags:
        - insomnia
    - include_tasks: tasks/mutt.yml
      tags:
        - mutt
    - include_tasks: tasks/ruby.yml
      tags:
        - install
        - ruby 
 
