- hosts: localhost 
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/ssh.yml
#    - include: tasks/git-setup.yml
#    - include: tasks/core-setup.yml
#    - include: tasks/node-setup.yml
#    - include: tasks/npm-packages.yml
#    - include: tasks/zsh-setup.yml
#    - include: tasks/slack-setup.yml
#    - include: tasks/personal-projects.yml
#    - include: tasks/nvim-setup.yml
#    - include: tasks/brave.yml
#    - include: tasks/dotfiles.yml
#    - include: tasks/productivity-tools.yml
