- hosts: localhost 
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/casks.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/npm-pkgs.yml
#    - include: tasks/zsh-setup.yml
#    - include: tasks/slack-setup.yml
#    - include: tasks/nvim-setup.yml
#    - include: tasks/dotfiles.yml
#    - include: tasks/productivity-tools.yml
