- hosts: localhost 
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tags:
      - install
      - core
  pre_tasks:
    - raw: ansible-galaxy install -r requirements.yml
  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
        - install
        - ssh
    - include_tasks: tasks/git.yml
      tags:
        - install
        - git
    - include_tasks: tasks/homebrew.yml
      tags:
        - install
        - homebrew
    - include_tasks: tasks/casks.yml
      tags:
        - install
        - casks
    - include_tasks: tasks/node.yml
      tags:
        - install
        - node
    - include_tasks: tasks/npm-pkgs.yml
      tags:
        - install
        - npm
    - include_tasks: tasks/zsh.yml
      tags:
        - zsh
        - install
    - include_tasks: tasks/java.yml
      tags:
        - install
        - java
    - include_tasks: tasks/dotfiles.yml
      tags:
        - install
        - dotfiles
    - include_tasks: tasks/softwareupdate.yml
      tags:
        - install
    - include_tasks: tasks/fonts.yml
      tags:
        - install
        - fonts
