- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/aaroncoville/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./macos
  tags:
    - dotfiles
- name: Ensure spotifyd directory exists for spotifyd.conf
  shell: mkdir -p ~/.config/spotifyd && rm -rf ~/spotifyd-cache && mkdir ~/spotifyd-cache 
  tags:
    - dotfiles
    - spotifyd
- name: Install spotifyd.conf
  copy:
    src: spotifyd/spotifyd.conf
    dest: ~/.config/spotifyd/spotifyd.conf
  tags:
    - dotfiles
    - spotifyd
