- name: Do all the Homebrew things
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages:
      - autoconf
      - awscli
      - bash
      - bash-completion
      - binutils
      - bison
      - coreutils
      - diffutils
      - docker-compose
      - ed
      - emacs
      - file-formula
      - findutils
      - flex
      - fortune
      - fzf
      - gawk
      - gimme-aws-creds
      - git
      - gpatch
      - grep
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - gzip
      - httpie
      - jq
      - less
      - libressl
      - m4
      - make
      - n
      - nano
      - neovim
      - nmap
      - openssh
      - openssl
      - perl
      - pyenv
      - pyenv-virtualenv
      - readline
      - reattach-to-user-namespace
      - rsync
      - screen
      - speedtest-cli
      - sqlite
      - stow
      - task
      - taskwarrior-tui
      - tmux
      - unzip
      - vim
      - watch
      - wdiff
      - wget
      - xz
      - yarn
      - zlib
      - zsh
    homebrew_upgrade_all_packages: true
    homebrew_cask_apps:
      - 1password
      - alacritty
      - brave-browser
      - docker
      - intellij-idea
      - insomnia
      - keybase
      - notion
      - setapp
    homebrew_taps:
      - homebrew/core
