- name: Ensure .ssh directory exists.
  file:
    dest: "{{ homedir }}/.ssh/"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "{{ item }}"
    dest: "{{ homedir }}/.ssh/"
    mode: 0600
  with_fileglob:
    - .ssh/id_ed25519
    - .ssh/personal_ed25519
  tags:
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ item }}" 
    dest: "{{ homedir }}/.ssh/" 
    mode: 0644
  with_fileglob:
    - .ssh/*.pub
  tags:
    - install
    - ssh
- name: Set authorized key from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}" 
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ homedir }}/.ssh/*.pub" 
