- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --keep-zshrc
- name: Install zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
- name: Install powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{homedir}}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
- name: Install tmux plugin manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: ~/.tmux/plugins/tpm
    update: yes
